schema_version: 1

context:
  name: httpx-retries
  version: "0.4.5"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/httpx_retries-${{ version }}.tar.gz
  sha256: acee306d7384eefad71ac12fefe8b13d7b41c19595c538e68d9bd7e40e59539d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - python >=${{ python_min }}
    - httpx >=0.20.0

tests:
  - python:
      imports:
        - httpx_retries
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: A retry layer for HTTPX
  description: |
    HTTPX Retries implements request retry for [HTTPX](https://www.python-httpx.org/).

    It's very common to deal with **flaky** and **unreliable** APIs.
    When requests fail, your program needs to be able to retry them.
  homepage: https://github.com/will-ockmore/httpx-retries
  repository: https://github.com/will-ockmore/httpx-retries
  documentation: https://will-ockmore.github.io/httpx-retries/

extra:
  recipe-maintainers:
    - will-ockmore
    - matthewfeickert
